# Generated by Django 4.2.1 on 2023-07-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('days', models.TextField(max_length=3)),
                ('amount', models.TextField(max_length=7)),
                ('quote', models.TextField(max_length=100)),
                ('place', models.TextField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
