# Generated by Django 4.2.1 on 2023-07-03 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_destinations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destinations',
        ),
    ]
