# Generated by Django 4.2.1 on 2023-07-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_delete_destinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.TextField(max_length=10)),
                ('amount', models.TextField(max_length=15)),
                ('quote', models.TextField(max_length=100)),
                ('place', models.TextField(max_length=50)),
            ],
        ),
    ]
