# Generated by Django 4.2.2 on 2023-07-18 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_destinations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destinations',
        ),
    ]
