# Generated by Django 4.2.2 on 2023-07-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_delete_destinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.TextField(max_length=10)),
                ('amount', models.TextField(max_length=15)),
                ('quote', models.TextField(max_length=100)),
                ('place', models.TextField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='media/')),
            ],
        ),
    ]
