# Generated by Django 4.2.2 on 2023-07-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_destinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
