# Generated by Django 4.2.2 on 2023-07-21 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0009_places_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('email', models.TextField(max_length=50)),
                ('traveldate', models.DateField()),
                ('adults', models.TextField(max_length=15)),
                ('phone', models.TextField(max_length=10)),
                ('aadhar', models.TextField(max_length=12, primary_key=True, serialize=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.places')),
            ],
        ),
    ]
