# Generated by Django 4.2.2 on 2023-07-25 05:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0013_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookplace', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('email', models.TextField(max_length=50)),
                ('traveldate', models.DateField()),
                ('adults', models.TextField(max_length=15)),
                ('phone', models.TextField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('aadhar', models.TextField(max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)])),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.places')),
            ],
        ),
    ]
