# Generated by Django 4.2.2 on 2023-08-03 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0014_places_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
