# Generated by Django 4.2.2 on 2023-08-03 08:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0015_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(max_length=50)),
                ('traveldate', models.DateField()),
                ('adults', models.TextField(max_length=15)),
                ('phone', models.TextField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('aadhar', models.TextField(max_length=12, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)])),
                ('amount', models.TextField(max_length=1000000)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.places')),
            ],
        ),
    ]
