# Generated by Django 4.2.2 on 2023-08-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0016_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='amount',
        ),
    ]
